---
###############################################################################
#                                                                             #
#                            WEBSITE CONFIGURATION                            #
#                                                                             #
###############################################################################


# --- base website settings ---

baseURL: https://sustainers.github.io/design/
title: "Design & UX, curated by Sustain"
theme: inventory
languageCode: en-us
enableEmoji: true
enableGitInfo: true
googleAnalytics: ""


# --- markup settings ---

markup:
  asciidocExt:
    preserveTOC: true
    sectionNumbers: true
  goldmark:
    renderer:
      unsafe: true
  highlight:
    anchorLineNos: false
    codeFences: true
    guessSyntax: false
    hl_Lines: ""
    lineAnchors: ""
    lineNoStart: 1
    lineNos: false
    lineNumbersInTable: true
    noClasses: true
    style: murphy
    tabWidth: 4


# --- privacy settings ---

privacy:
  googleAnalytics:
    anonymizeIP: true
    respectDoNotTrack: true
  twitter:
    enableDNT: true
  vimeo:
    enableDNT: true
  youtube:
    privacyEnhanced: true


# --- navigation menu ---

menu:
  main:
    - name: FAQ
      weight: 10
      url: faq

    - name: pages
      weight: 20
      url: pages
      hasChildren: true

    - name: Defining Design
      parent: pages
      weight: 10
      url: definitions

    - name: For the maintainers
      parent: pages
      weight: 20
      url: maintainers

    - name: For the designers
      parent: pages
      weight: 30
      url: designers

    - name: Guidelines & frameworks
      parent: pages
      weight: 40
      url: guidelines

    - name: Case studies & examples
      parent: pages
      weight: 50
      url: examples


# --- custom settings ---

params:
  logo: "images/logo.png"

  # OpenGraph data
  description: Inventory of design resources, best practices, and content about design contributions in Open Source.
  author: SustainOSS Design & UX Working Group
  image: "images/UNI309823.jpg"

  # customize color
  primary_color: "#32c6b0"
  body_color: "#D8D1C9"
  text_color: "#777779"
  text_color_dark: "#374EA2"
  text_title_color: "#264959ff"
  white_color: "#ffffff"
  light_color: "#f8f9fa"

  # font family (choose from https://fonts.google.com/)
  font_family: "Open+Sans"

  # contact form action (works with https://formspree.io)
  contact_form_action: "#"

  # related article number limit
  article_count: 3

  # brand and identity information
  brand:
    parent_org_name: SustainOSS
    parent_org_url: https://sustainoss.org/
    parent_org_url_legal: https://sustainoss.org/privacy/
  footer:
    mainSite: https://discourse.sustainoss.org/c/working-groups/design/25
    mainSiteName: Discourse @ SustainOSS
    description: Inventory of design resources, best practices, and content about design contributions in Open Source.


# --- social platform settings ---

# themify icon pack : https://themify.me/themify-icons

  social:
    - icon: ti-github
      name: SustainOSS on GitHub
      link: https://github.com/sustainers/design
    - icon: ti-twitter
      name: "@SustainOSS on Twitter"
      link: https://twitter.com/SustainOSS


# --- taxonomy settings ---

taxonomies:
  alert: alerts
  category: categories
  downloadable: downloadBtn


# --- multilingual settings ---

Languages:
############################# English #############################
  en:
    languageName: en
    languageCode: en-us
    weight: 1
    home: Home
    copyright: Creative Commons BY-SA 4.0. Site theme adapted from UNICEF Inventory theme.
    params:
      banner:
        title: Design & UX
        subtitle: Inventory of design resources, best practices, and content about design contributions in Open Source.
        # Photo by Hal Gatewood on Unsplash.
        bg_image: images/banner.jpg
        placeholder: Have a question? Search the site here.
############################# Español / Spanish #############################
  # es:
  #   languageName: es
  #   languageCode: es-mx
  #   weight: 2
  #   home: Página principal
  #   copyright: Creative Commons BY-SA 4.0.
  #   params:
  #     banner:
  #       title: "Inventario de Open Source de UNICEF"
  #       subtitle: "Una base de conocimientos de innovación mundial del UNICEF sobre mejores prácticas y recursos para trabajar y dirigir Open."
  #       bg_image: images/banner.jpg
  #       placeholder: ¿Tienes una pregunta? Busque en el sitio aquí.
